import { StyleSheet } from "react-native";

export const MealTrackingStyles = StyleSheet.create({
    HeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingTop: 10,
    },
    HeaderStackedColumn: {
        flex: 1,
        justifyContent: 'space-between',
    },
    HeaderBox: {
        flex: 1,
    },
    HeaderSeparator: {
        width: 2,
        backgroundColor: 'white',
        marginHorizontal: 0,
        borderRadius: 0,
    },
    TrackingOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        paddingTop: 4,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        justifyContent: "center",
        alignItems: "center",
    },
    TrackingOptionsContainer: {
        width: "100%",
        height: "100%",
        backgroundColor: "#0d0d0d",
        padding: 0,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#2a2a2a',
        overflow: 'hidden'
    },
    TrackingBackButton: {
        alignSelf: "flex-start",
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        marginLeft: 10,
        marginBottom: 4,
        paddingVertical: 6,
        paddingHorizontal: 14,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    MealOptionOuterContainer: {
        minHeight: 115,
        paddingVertical: 6,
        flex: 1,
        flexDirection: 'column',
        padding: 5,
        paddingHorizontal: 16,
    },
    MealOptionLayoutContainer: {
        minHeight: 115,
        flex: 1,
        flexDirection: 'column',
        padding: 10,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#2a2a2a",
        backgroundColor: "#161616",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 4,
    },
    MealInfoButton: {
        position: 'absolute',
        right: -15, // Half of the child width (if width = 100)
        top: '60%',
        transform: [{ translateY: -15 }], // Half of child height (if height = 50), + 10px lower
        width: 40,
        height: 40,
        backgroundColor: '#1c1c1c',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 50,
        borderColor: '#3a3a3a',
        borderWidth: 1
    },
    MealSizeButton: {
        position: 'absolute',
        right: -15, // Half of the child width (if width = 100)
        top: '60%',
        transform: [{ translateY: -25 }], // Half of child height (if height = 50)
        width: 40,
        height: 40,
        backgroundColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 50,
        borderColor: 'grey',
        borderWidth: 1
    },
    AddMealButton: {
        flex: 0.5,
        flexDirection: 'column',
        paddingVertical: 6,
        paddingHorizontal: 0,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "rgba(50,205,50,0.6)",
        backgroundColor: "rgba(50,205,50,0.12)",
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center'
    },
    WaterOptionOuterContainer: {
        minHeight: 100,
        paddingVertical: 5,
        flex: 1,
        flexDirection: 'column',
        padding: 5,
        backgroundColor: "black"
    },
    WaterOptionLayoutContainer: {
        minHeight: 100,
        flex: 1,
        flexDirection: 'column',
        padding: 15,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: "white",
        backgroundColor: "black"
    },
    AddWaterButton: {
        flex: 0.3,
        flexDirection: 'column',
        padding: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: "lime",
        backgroundColor: "black",
        justifyContent: 'center'
    },
    WaterAmountBlock: {
        flex: 0.5,
        flexDirection: 'column',
        paddingLeft: 0,
        backgroundColor: "black",
        justifyContent: 'center'
    },
    WaterAmountText: {
        color: 'white',
        fontSize: 26,
        textAlign: 'center'
    },
    WaterIconsBlock: {
        flex: 0.2,
        flexDirection: 'column',
        padding: 10,
        backgroundColor: "black",
        justifyContent: 'center'
    },
    WaterIconsRow: {
        flex: 0.5,
        flexDirection: 'row',
        backgroundColor: "black",
        justifyContent: 'center',
    },
    WaterIconsIconContainer: {
        flex: 0.5,
        flexDirection: 'column',
        borderColor: 'black',
        borderWidth: 1,
        backgroundColor: "black",
        justifyContent: 'center',
        alignItems: 'center',
    },
    WaterIconsText: {
        alignItems: 'center',
    },
    WaterCustomBlock: {
        flex: 0.65,
        flexDirection: 'column',
        paddingHorizontal: 10,
        backgroundColor: "black",
        justifyContent: 'center',
    },
    WaterCustomUnitsBlock: {
        flex: 0.05,
        flexDirection: 'column',
        paddingLeft: 0,
        backgroundColor: "black",
        justifyContent: 'center'
    },
    InstructionsOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        paddingTop: 4,
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        justifyContent: "center",
        alignItems: "center",
    },
    MealCategoryCard: {
        flex: 1,
        backgroundColor: "#161616",
        borderWidth: 1,
        borderRadius: 16,
        borderColor: "white",
        paddingHorizontal: 14,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 4,
    },
    MealCategoryHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    MealCategoryIconBadge: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.06)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    MealCategoryTitle: {
        color: 'white',
        fontSize: 17,
        fontWeight: '600',
    },
    MealCategoryTitleDivider: {
        height: 1,
        backgroundColor: 'white',
        marginBottom: 4,
    },
    MealItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.06)',
    },
    MealItemName: {
        color: 'white',
        fontSize: 15,
    },
    MealItemCalories: {
        color: '#cfcfcf',
        fontSize: 14,
        textAlign: 'right',
    },
    MealAddFoodButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginTop: 4,
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.04)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
})

